name: SprayCan Group
favicon: null
layout_spectrum: 1
typography_spectrum: 0.27211
title: SprayCan Group - Digital Marketing and Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8dc641'
    - '#85a451'
    - '#63625e'
    - '#313740'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
